### ISSUE TITLE
Plan to integrate your Label Attention into Transformers

### ISSUE THREAD

**Issue by hankcs** [KhalilMrini/LAL-Parser#1]
Hi Khalil, I've read your wonderful paper "Rethinking Self-Attention: An Interpretable Self-Attentive Encoder-Decoder Parser", which inspired me. I have been seeking for a way to make attention work with labels (especially parsing labels) and your LAL is a fantastic approach for that purpose. I'm thinking if there exists a way to replace the self-attention layer in transformers with some novel layers like LAL giving that the downstream task is label related. If that works, the number of parameters will be reduced and we will have a dedicated parsing architecture with probably better performance.

My question is, do you have any updates on releasing your code? Even a preliminary version is fine too. Thanks.

**Comment by KhalilMrini** [comment]
Hi, Thank you so much for your interest in our work! We are sorry for the late reply, we have the right to release the code now. Please check it out and send me any questions you may have, I will be very happy to respond.
