### ISSUE TITLE
how much cuda memeory the model needs when training ？

### ISSUE THREAD

**Issue by wangwang110** [KhalilMrini/LAL-Parser#13]
how much cuda memeory the model needs when training ？ and does it support multi-gpu training ？

**Comment by KhalilMrini** [comment]
Hi, the best model was trained on a single 32GB GPU. I tried developing multi-gpu training, but PyTorch is not geared towards that.

**Comment by Franck-Dernoncourt** [comment]
The paper ["Rethinking Self-Attention: Towards Interpretability in Neural Parsing" (Mrini et al., 2020)](https://arxiv.org/pdf/1911.03875v2.pdf) mentions:

> Each English experiment is performed on a single 32GB GPU, while each Chinese experiment is
performed on a single **12GB GPU**.

Why does the GPU memory requirement differ between the Chinese experiment and English experiment?
