### ISSUE TITLE
download the best model

### ISSUE THREAD

**Issue by CCChenhao997** [KhalilMrini/LAL-Parser#15]
Can you upload the best model through Baidu Netdisk, because it's not convenient for Google Drive to download large files. 
Thank you very much.

**Comment by Franck-Dernoncourt** [comment]
What's the issue with Google Drive to download large files? (Google ban in China or something else?)

**Comment by Franck-Dernoncourt** [comment]
Mirror: https://archive.org/details/neuraladobe-ucsdparser

To download it programmatically:
```
pip install internetarchive
ia download neuraladobe-ucsdparser
```

**Comment by CCChenhao997** [comment]
> Mirror: https://archive.org/details/neuraladobe-ucsdparser
> 
> To download it programmatically:
> 
> ```
> pip install internetarchive
> ia download neuraladobe-ucsdparser
> ```

I have solved the download model problem. Thank you. I really appreciate your help.
