### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Sharefah-Alghamdi** [KhalilMrini/LAL-Parser#18]
Hi
Thank you for sharing your code!
I ran your training code in your dataset and it works perfectly!
but when I try to run it on my own Arabic dependency treebank (without changing your paths for constituency data set - I don't have a constituency treebank for my dataset) I get the following error.

Could you help me please to fix it?

********************
**Reading dependency parsing data from data/padt.train.conllu
Reading dependency parsing data from data/padt.dev.conllu
Total number of data: 6075
Loading training trees from data/02-21.10way.clean...
Traceback (most recent call last):
  File "src_joint/main.py", line 788, in <module>
    main()
  File "src_joint/main.py", line 784, in main
    args.callback(args)
  File "src_joint/main.py", line 727, in <lambda>
    subparser.set_defaults(callback=lambda args: run_train(args, hparams))
  File "src_joint/main.py", line 230, in run_train
    train_treebank = trees.load_trees(train_path, dep_heads, dep_types, dep_sentences)
  File "/content/gdrive/My Drive/LAL-Parser/src_joint/trees.py", line 285, in load_trees
    trees, index = helper(0, flag_sent = 1)
  File "/content/gdrive/My Drive/LAL-Parser/src_joint/trees.py", line 261, in helper
    children, index = helper(index, flag_sent = 0)
  File "/content/gdrive/My Drive/LAL-Parser/src_joint/trees.py", line 261, in helper
    children, index = helper(index, flag_sent = 0)
  File "/content/gdrive/My Drive/LAL-Parser/src_joint/trees.py", line 261, in helper
    children, index = helper(index, flag_sent = 0)
  [Previous line repeated 5 more times]
  File "/content/gdrive/My Drive/LAL-Parser/src_joint/trees.py", line 269, in helper
    trees.append(LeafTreebankNode(label, word, head = cun_word + 1, father=heads[cun_sent][cun_word], type = types[cun_sent][cun_word]))
IndexError: list index out of range**

**Comment by Dhurim** [comment]
I get the same error, but I remove the lines for dependency treebanks and I give paths to my constituency dataset. The problem is for the first row of data set it works fine, starting from second row, after the 4th word it gets this error.

**Comment by Sharefah-Alghamdi** [comment]
> I get the same error, but I remove the lines for dependency treebanks and I give paths to my constituency dataset. The problem is for the first row of data set it works fine, starting from second row, after the 4th word it gets this error.

thank you for your reply

I found the reason. It was the first line of the dataset that contains the sentence:
#="sentence .."

**Comment by Dhurim** [comment]
Hi Sharefah, could you please give me more details, is there any possibility for me to contact you. I still get this error and I would appreciate if you help me resolve it.

**Comment by Sharefah-Alghamdi** [comment]
> Hi Sharefah, could you please give me more details, is there any possibility for me to contact you. I still get this error and I would appreciate if you help me resolve it.

sorry for being late!
I just see your reply.

Yes. you are welcome.
my email is
sharefahATksuDOTeduDOTsa
