### ISSUE TITLE
Dependency Parsing only

### ISSUE THREAD

**Issue by Sharefah-Alghamdi** [KhalilMrini/LAL-Parser#20]
Hi
Is there any way to train the model on my own dataset for only the dependency parsing while I don't have the constituency annotaion for the same data?
Thank you

**Comment by Sharefah-Alghamdi** [comment]
I see that you use the joint spn representation.

**Comment by Sharefah-Alghamdi** [comment]
I see that you use the joint spn representation.

**Comment by LifeIsStrange** [comment]
@Sharefah-Alghamdi did you find a way to exclude consitutuency data?
