### ISSUE TITLE
Can't seem to use the model

### ISSUE THREAD

**Issue by nishan-chatterjee** [KhalilMrini/LAL-Parser#25]
I followed the same process mentioned under the Inference step. I get this error for both parse.sh and parse_quick.sh. What am I doing wrong? I'm working on a server where I don't have admin access, so I can't upgrade pip.

sh parse_quick.sh 
Not using CUDA!
Loading model from best_parser.pt...
Some weights of the model checkpoint at xlnet-large-cased were not used when initializing XLNetModel: ['lm_loss.bias', 'lm_loss.weight']
- This IS expected if you are initializing XLNetModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLNetModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
/bigpool/projects/chatterjee/graphVD/modelData/neural-parser/neural-parser/lib/python3.10/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Parsing sentences...
Parsing sentences:   0%|                                                          | 0/1 [00:00<?, ?it/s]/bigpool/projects/chatterjee/graphVD/modelData/neural-parser/LAL-Parser/src_joint/KM_parser.py:1754: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:1665.)
  features_packed = features.masked_select(all_word_end_mask.to(DTYPE).unsqueeze(-1)).reshape(-1,
/bigpool/projects/chatterjee/graphVD/modelData/neural-parser/LAL-Parser/src_joint/KM_parser.py:230: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:1582.)
  attn.data.masked_fill_(attn_mask, -float('inf'))
/bigpool/projects/chatterjee/graphVD/modelData/neural-parser/LAL-Parser/src_joint/KM_parser.py:397: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at  ../aten/src/ATen/native/IndexingUtils.h:28.)
  outputs = outputs_padded[output_mask]
Parsing sentences:   0%|                                                          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/bigpool/projects/chatterjee/graphVD/modelData/neural-parser/LAL-Parser/src_joint/main.py", line 788, in <module>
    main()
  File "/bigpool/projects/chatterjee/graphVD/modelData/neural-parser/LAL-Parser/src_joint/main.py", line 784, in main
    args.callback(args)
  File "/bigpool/projects/chatterjee/graphVD/modelData/neural-parser/LAL-Parser/src_joint/main.py", line 711, in run_parse
    syntree, _ = parser.parse_batch(tagged_sentences)
  File "/bigpool/projects/chatterjee/graphVD/modelData/neural-parser/LAL-Parser/src_joint/KM_parser.py", line 1771, in parse_batch
    annotations, self.current_attns = self.encoder(emb_idxs, pre_words_idxs, batch_idxs, extra_content_annotations=extra_content_annotations)
  File "/bigpool/projects/chatterjee/graphVD/modelData/neural-parser/neural-parser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/bigpool/projects/chatterjee/graphVD/modelData/neural-parser/LAL-Parser/src_joint/KM_parser.py", line 1170, in forward
    res, current_attns = attn(res, batch_idxs)
  File "/bigpool/projects/chatterjee/graphVD/modelData/neural-parser/neural-parser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/bigpool/projects/chatterjee/graphVD/modelData/neural-parser/LAL-Parser/src_joint/KM_parser.py", line 404, in forward
    return self.layer_norm(outputs + residual), attns_padded
RuntimeError: The size of tensor a (39) must match the size of tensor b (35) at non-singleton dimension 0

**Comment by nishan-chatterjee** [comment]
I was working with the wrong torch version. Ran into legacy issues.

**Comment by James-Decatur** [comment]
> I was working with the wrong torch version. Ran into legacy issues.

Yeah, but how did you fix that?

I'm trying to get it to work on Google Colab and I am running into the same issue...

"RuntimeError: The size of tensor a (336) must match the size of tensor b (209) at non-singleton dimension 0"

**Comment by nishan-chatterjee** [comment]
I used a conda env with python3.6 or 3.7 on a server. Didn't try it on Colab. Sorry.

**Comment by James-Decatur** [comment]
Yeah so, to run it on Google Colab you do the following:

After connecting to Google Drive...

# Step One - Clone It
!git clone https://github.com/KhalilMrini/LAL-Parser.git

# Step Two - The New Requirements
!pip install torch
!pip install cython
!pip install numpy
!sudo apt-get install libhdf5-dev
!pip install benepar[gpu]
!pip install pytorch_pretrained_bert
!pip install sentencepiece
!pip install tensorflow
!pip install tensorboard
!pip install nltk
!python3 -m nltk.downloader punkt averaged_perceptron_tagger
!pip install git+https://github.com/lanpa/tensorboardX
!pip install transformers
!pip install tqdm
!pip install gdown
!gdown https://drive.google.com/uc?id=1LC5iVcvgksQhNVJ-CbMigqXnPAaquiA2

# Step 3 - Don't Forget Glove
"Go and get 'Glove.6B.100d.text.gz' or something synonymous, unzip it, and stick it in your Google Drive under the name 'glove.gz'.

# Step 4 - Update KM_Parser.py, main.py, and best_parser_training_script.sh

[best_parser_training_script.txt](https://github.com/KhalilMrini/LAL-Parser/files/11549588/best_parser_training_script.txt)

[KM_parser.txt](https://github.com/KhalilMrini/LAL-Parser/files/11549590/KM_parser.txt)

[main.txt](https://github.com/KhalilMrini/LAL-Parser/files/11549592/main.txt)

# Step 5 - Create Empty 'models' Folder
Put it under/in 'LAL-Parser'

# Step 6 - Run It.
!sh LAL-Parser/best_parser_training_script.sh

P.S. - If you don't have COLAB PRO+ you might run into an issue with the " --batch-size 100" in the training script.
