### ISSUE TITLE
Not able to download pretrained model

### ISSUE THREAD

**Issue by fallcat** [KhalilMrini/LAL-Parser#28]
Hi! Thank you for the great work! I'm trying to use the pretrained model, but there is a permission denial when I clicked on the link to the google drive for the best model. I sent a request for access. Could you please take a look? Thank you so much!

**Comment by Franck-Dernoncourt** [comment]
Sorry about that, here is a mirror where you can download it:  https://archive.org/download/neuraladobe-ucsdparser

**Comment by fallcat** [comment]
Thank you so much!!
