### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by DianaKazakova** [KhalilMrini/LAL-Parser#31]
Hello,
I want to use LAL parser for the ABSA task that I have, but I have a problem with permission denied for the link of the model https://drive.google.com/file/d/1LC5iVcvgksQhNVJ-CbMigqXnPAaquiA2/view?usp=sharing

**Comment by Franck-Dernoncourt** [comment]
Sorry about that, here is a mirror where you can download it: https://archive.org/download/neuraladobe-ucsdparser

@KhalilMrini Can you please merge https://github.com/KhalilMrini/LAL-Parser/pull/29 when you get a chance? thanks :)

**Comment by KhalilMrini** [comment]
Done! Closing this issue
