### ISSUE TITLE
Slow parsing speed

### ISSUE THREAD

**Issue by ZhaofengWu** [KhalilMrini/LAL-Parser#7]
Hi, thanks for publishing the code and the model! I'm trying to use the model to parse some sentences using the `parse.sh` script, but it's been very slow. With the default eval batch size of 50, it is taking 100-400s per batch on an RTX 8000. Is that expected?

**Comment by KhalilMrini** [comment]
Hi Zhaofeng, thank you so much for your interest in our work! I am really pleased that you are using our model.
Actually, the `parse.sh` script computes head contributions, which takes a lot of time. I added a script `parse_quick.sh` that does not compute head contributions, and just parses sentences. I hope that helps!
