### ISSUE TITLE
RuntimeError: Trying to create tensor with negative dimension -1: [-1, 1024]

### ISSUE THREAD

**Issue by zhaoyanpeng** [KhalilMrini/LAL-Parser#8]
Hi nice code! Thanks for making it publicly available.

Following your example of running the inference code in a python virtual environment I encountered the following error:
```
Loading model from /home/s1847450/code/neural-parser/model/best_parser.pt...
Traceback (most recent call last):
  File "src_joint/main.py", line 771, in <module>
    main()
  File "src_joint/main.py", line 767, in main
    args.callback(args)
  File "src_joint/main.py", line 644, in run_parse
    parser = KM_parser.ChartParser.from_spec(info['spec'], info['state_dict'])
  File "/disk/nfs/ostrom/s1847450/code/neural-parser/LAL-Parser/src_joint/KM_parser.py", line 1436, in from_spec
    res = cls(**spec)
  File "/disk/nfs/ostrom/s1847450/code/neural-parser/LAL-Parser/src_joint/KM_parser.py", line 1266, in __init__
    self.xlnet_tokenizer, self.xlnet = get_xlnet(hparams.xlnet_model, hparams.xlnet_do_lower_case)
  File "/disk/nfs/ostrom/s1847450/code/neural-parser/LAL-Parser/src_joint/KM_parser.py", line 684, in get_xlnet
    xlnet = XLNetModel.from_pretrained(xlnet_model)
  File "/disk/nfs/ostrom/s1847450/code/neural-parser/LAL-Parser/src_joint/pytorch_transformers/modeling_utils.py", line 474, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/disk/nfs/ostrom/s1847450/code/neural-parser/LAL-Parser/src_joint/pytorch_transformers/modeling_xlnet.py", line 736, in __init__
    self.word_embedding = nn.Embedding(config.n_token, config.d_model)
  File "/disk/nfs/ostrom/s1847450/code/neural-parser/pyenv/neural-parser/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 99, in __init__
    self.weight = Parameter(torch.Tensor(num_embeddings, embedding_dim))
RuntimeError: Trying to create tensor with negative dimension -1: [-1, 1024]
```
Is it because the pre-trained model you provided is outdated? After searching for a while I found a similar issue here [https://github.com/huggingface/transformers/issues/4094#issue-610665902](https://github.com/huggingface/transformers/issues/4094#issue-610665902). It might be helpful for analyzing the issue.

**Comment by KhalilMrini** [comment]
Hi Yanpeng,

Thank you so much for your interest in our work! I am going to check this error, I believe this is indeed due to an update. Thanks for alerting me.

**Comment by Franck-Dernoncourt** [comment]
(same issue when running the Docker example)

**Comment by zhaoyanpeng** [comment]
Hi Khalil,

Just wondering if you are working on this issue? I am looking for a pre-trained dependency parsing model. It would be nice if I can use the best one, as far as I know, that is your model.

Thanks in advance.

**Comment by lytum** [comment]
I also have the same issue. two weeks ago, everything is ok. Today, just try to run the same code, however, I got the 'negative dimension' error. Thanks in advance for any updates.

**Comment by lytum** [comment]
oh, I just solved the issue. Just change 
'from pytorch_transformers import XLNetForSequenceClassification'
 to 
'from transformers import XLNetForSequenceClassification'. 
from library 'transformers' import everything.

**Comment by Franck-Dernoncourt** [comment]
Thanks! Do you know how comes the issue arose even though we specified the version of `pytorch_transformers` in https://github.com/KhalilMrini/LAL-Parser/blob/master/requirements.sh (   `pip install pytorch_pretrained_bert==0.6.2`)? I thought the point of specifying versions was to avoid the kind of issues (since I thought the code for a given version isn't supposed to change) :-/

**Comment by zhaoyanpeng** [comment]
Hi @lytum, which commit are you on? I tried the same solution as yours before, but it did not work.

**Comment by KhalilMrini** [comment]
Hi all,

@lytum  is right, the problem is that there was an update on an online config file for XLNet. As a result, the value of `config.n_token` is not found and ends up being `-1`. I just updated the code, please let me know if that works from your side @zhaoyanpeng .

**Comment by KhalilMrini** [comment]
I just tried the code with the latest commit and it works with the command `sh parse_quick.sh`.

**Comment by zhaoyanpeng** [comment]
Hi @KhalilMrini. I got a new error. Is it caused by `libhdf5-serial-dev=1.8.16+docs-4ubuntu1.1`? I cannot install it on my OS. I have carefully checked other dependency modules. They satisfy version requirements specified in `requirements.sh`.
```
Loading model from best_parser.pt...
Traceback (most recent call last):
  File "/disk/nfs/ostrom/s1847450/code/neural-parser/pyenv/neural-parser/lib/python3.6/site-packages/transformers/modeling_utils.py", line 516, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location="cpu")
  File "/disk/nfs/ostrom/s1847450/code/neural-parser/pyenv/neural-parser/lib/python3.6/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/disk/nfs/ostrom/s1847450/code/neural-parser/pyenv/neural-parser/lib/python3.6/site-packages/torch/serialization.py", line 581, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 7276097 more bytes. The file might be corrupted.
```
Here are outputs from `pip list`:
```
Package                 Version
----------------------- -----------
absl-py                 0.9.0
astor                   0.8.1
benepar                 0.1.2
boto3                   1.13.2
botocore                1.16.2
cachetools              4.1.0
certifi                 2020.4.5.1
chardet                 3.0.4
click                   7.1.2
Cython                  0.29.13
dataclasses             0.7
docutils                0.15.2
filelock                3.0.12
gast                    0.2.2
google-auth             1.14.1
google-auth-oauthlib    0.4.1
google-pasta            0.2.0
grpcio                  1.28.1
h5py                    2.10.0
idna                    2.9
jmespath                0.9.5
joblib                  0.14.1
Keras-Applications      1.0.8
Keras-Preprocessing     1.1.0
Markdown                3.2.1
nltk                    3.5
numpy                   1.17.2
oauthlib                3.1.0
opt-einsum              3.2.1
pip                     20.1
protobuf                3.11.3
pyasn1                  0.4.8
pyasn1-modules          0.2.8
python-dateutil         2.8.1
pytorch-pretrained-bert 0.6.2
regex                   2020.4.4
requests                2.23.0
requests-oauthlib       1.3.0
rsa                     4.0
s3transfer              0.3.3
sacremoses              0.0.43
scipy                   1.4.1
sentencepiece           0.1.83
setuptools              46.1.3
six                     1.14.0
tensorboard             2.0.0
tensorboardX            2.0+022f060
tensorflow              2.0.0
tensorflow-estimator    2.0.1
tensorflow-gpu          2.0.0
termcolor               1.1.0
tokenizers              0.5.2
torch                   1.1.0
tqdm                    4.46.0
transformers            2.8.0
urllib3                 1.25.9
Werkzeug                1.0.1
wheel                   0.34.2
wrapt                   1.12.1
```

**Comment by Franck-Dernoncourt** [comment]
"RuntimeError: unexpected EOF, expected 7276097 more bytes. " makes me
wonder whether the download of best_parser.pt was incomplete/corrupt.

**Comment by zhaoyanpeng** [comment]
It seems so. Mind comparing your md5 hash with my downloaded model?
`e5f5c7758d0ba9cd63bf16c5ffe2b5d6  best_parser.pt`

**Comment by Franck-Dernoncourt** [comment]
Same hash:

```
docker run --interactive --tty ubuntu:18.04 bash
apt update; apt install -y git nano wget htop python3 python3-pip unzip; git clone https://github.com/KhalilMrini/LAL-Parser
cd LAL-Parser/
alias pip=pip3; source requirements.sh
md5sum best_parser.pt
e5f5c7758d0ba9cd63bf16c5ffe2b5d6  best_parser.pt
```

so now I'm guessing the download of some pretrained model from the `transformers` python package is incomplete/corrupt. Clear them or use add some `force_download` option when retrieving the pretrained models.

**Comment by Franck-Dernoncourt** [comment]
By the way @zhaoyanpeng  can you please create a new issue for your new issue? thanks :)

**Comment by zhaoyanpeng** [comment]
Sorted out. 
I ran the model on another machine and it went through. Still curious about the weird issue. Let me know if you would like to figure it out. I can share with you my installation logs. Thank you all for the helpful discussion!

**Comment by Franck-Dernoncourt** [comment]
I'm guessing the download of some pretrained model from the `transformers` python package is incomplete/corrupt. Clear them or use add some `force_download` option when retrieving the pretrained models.

**Comment by zhaoyanpeng** [comment]
That might be the cause. I actually cleared all pip caches and deleted pyenv before a fresh installation, but the error still occurred.

**Comment by Franck-Dernoncourt** [comment]
does clearing all pip caches also clear transformers' pre-trained models? (if you don't know, then after you clear pip cache, run  `source parse.sh` and see whether it downloads transformers' pre-trained models)

**Comment by zhaoyanpeng** [comment]
Not sure. I guess not. Do you know which location the transformers use by default to store pre-trained models? I have been searching for it but did not get an answer.

**Comment by Franck-Dernoncourt** [comment]
When running `source parse.sh` you should see `Downloading` if transformers' pre-trained models are being downloaded (e.g. see below). If you don't see, then you're using the cache.

```
Loading model from best_parser.pt...
Downloading: 100%|#################################################################################################################################################################################| 798k/798k [00:00<00:00, 1.88MB/s]
Downloading: 100%|####################################################################################################################################################################################| 737/737 [00:00<00:00, 283kB/s]
Downloading:  11%|###################3       
```

**Comment by zhaoyanpeng** [comment]
Yes, you are right. I just finished another fresh installation. This time I deleted `~/.cache/torch/*`. Pre-trained models were being downloaded. Tests passed. Thank you very much for helping fix this issue :)

**Comment by Franck-Dernoncourt** [comment]
You're welcome, glad that the issue is fixed!
